spring:
  application:
    name: livraria-api
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 70973552386-ku59rucvig4lsqp39m80p8in0ef9n949.apps.googleusercontent.com
            client-secret: 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